### ISSUE TITLE
Update the validation script

### ISSUE THREAD

**Issue by mn5hk** [mn5hk/pyshbundle#101]
http://localhost:8888/notebooks/notebooks%2F03_validation_pyshbundle.ipynb

**Comment by mn5hk** [comment]
http://localhost:8888/notebooks/master.ipynb

**Comment by abhimhamane** [comment]
I have tried to update certain things, but I don't think I could do it.

**Comment by lsmvivek** [comment]
2024-06-11
Done, repo https://github.com/lsmvivek/pyshbundle/tree/main; waiting to merge

**Comment by mn5hk** [comment]
Hi @lsmvivek, the branch is [23 commits ahead of](https://github.com/lsmvivek/pyshbundle/compare/mn5hk%3Apyshbundle%3Amain...main), [14 commits behind](https://github.com/lsmvivek/pyshbundle/compare/main...mn5hk%3Apyshbundle%3Amain) mn5hk/pyshbundle:main.

Could you try to git pull the main repository before pushing your changes? There might be merge inconsistencies with the current push
