### ISSUE TITLE
Introduction - entry points, example codes

### ISSUE THREAD

**Issue by mn5hk** [mn5hk/pyshbundle#25]

**Comment by mn5hk** [comment]
Hi @abhimhamane, thank you for approaching and your interest in the project. I will get back in a couple days with something concrete.

Also cc-ing @lsmvivek to keep him in the loop.

**Comment by abhimhamane** [comment]
@mn5hk Thank you for your response. Till then, I'll familiarize myself with the codebase.

**Comment by mn5hk** [comment]
Dear Abhishek,

Apologies for the delay in communication. I recently moved cities, and have
been slow in my responses.

I am pleased of your interest in the pyshbundle package. Further, it is
good to know of your prior experience with SHbundle as well as your
experience with Python as reflected with our brief interactions on github.
We would be pleased to have your contributions to the package. I request
all modifications being made by you to be made first in a *new branch*, and
then consulted before merging it.

There are few issues where we could use your help at the moment. Firstly,
the paper.md file is not rendering the way it should. Secondly,
documentation needs to be improved. Moreover, there are works that can be
done to further improve functionalities of the module. However, we will
have this on hold for now. Depending on your interest and availability, we
will see if we can engage you later on developing more features, however
for now, we focus on finalizing the package for release. I will add more
details on the task in the github issues section; which will be the primary
mode of communication for feature enhancements.

Currently, we are planning to publish a software paper out of the work. We
believe the package consolidates a few existing techniques for processing
GRACE data into a Python package and adds value to the geodetic programming
community. I am further pleased to invite you to be one of the co-authors
of the paper being drafted, subject to your contributions.

Lastly, in the email, I have cc-ed Dr. Bramha (Assistant Prof., ICWaR,
IISc), Vivek (PhD candidate, ICWaR) and Dr. Maya (Postdoc, ICWaR). The
project started nearly a year ago under the supervision of Dr. Bramha.
Vivek has been heavily involved in the project from its inception, while
Dr. Maya has also recently joined the team on the same. Good to have
everyone in the loop while we welcome a new contributor to our project!

Thanks Abhishek, once again for your keen interest. See you more often on
github.

Best,
Amin Shakya
Enschede, the Netherlands

**Comment by mn5hk** [comment]
Hi @abhimhamane, I have shared a response via email. Please let me know in case you have not received it.

I will start assigning some tasks to you on Github. Fell free to contact me in case of any confusion.

Best,
AS

**Comment by abhimhamane** [comment]
Hello Amin,

Thanks a lot for making me a collaborator on this project. I look forward
to contributing something meaningful towards this open-source project. I'm
still learning things related to Geodesy and Python programming, like today
troubleshooting the LaTeX math and GitHub Actions issues; I learned a lot
of new things. As you mentioned, starting with documentation is better
before I can work on new functionalities. I'll finish my coursework this
semester and then can focus entirely on my thesis and this project.

I'm highly honoured by your offer of co-authorship, and for that I need to
make more big-impact contributions.

Once again, thank you very much for making me a collaborator on this
project.

Regards,
Abhishek Mhamane
MS-R Geoinformatics
IIT Kanpur
