### ISSUE TITLE
Revise paper.md

### ISSUE THREAD

**Issue by mn5hk** [mn5hk/pyshbundle#33]
On 2023-2-2, we had an update meeting where we've looked at the current paper draft status. Few updates to be made to the paper draft as agreed:

- [x] Update technical descriptions on the paper draft @mn5hk 
- [x] - [x] Validation of the script for a few basins and maybe also a few points or grid areas [@lsmvivek]
- [x] Add some mathematical relationships/appropriate  [@Walling9]
- [x] Add some appropriate diagrams of Gaussian filter, spherical harmonics; make diagrams ourselves if possible [@Walling9 , @lsmvivek ]
- [x] Improvise on the current flowchart; make alternative workflow diagrams [@mn5hk , @lsmvivek ]
- [x] Improve our citations of relevant literature [@mn5hk ]
- [x] Write an abstract
- [x] Elaborate GDDC [ @mn5hk ]
- [x] Review few existing tools for GRACE processing [@mn5hk]
- [x] Does GIA need to be removed for the latest version of GRACE SH data?
- [x] Feng (2018) has estimated GRACE measurement error by obtaining RMS over oceans at the same latitude as the study region. How reliable is the method? Also check: Chen JL, Wilson CR, Tapley BD, Yang ZL, Niu GY (2009b) 2005
drought event in the Amazon River basin as measured by GRACE and estimated by climate models. J Geophys Res 114:B05404. https://doi.org/10.1029/2008jb006056 

- [x]   Wahr et al. (2006) used the second method to determine the uncertainties in the GRACE SH coefficients as
the standard deviation of the residuals of coefficients when seasonal cycles were removed. This method may also overestimate the GRACE measurement error because we assume that all non-seasonal variability of Stokes coefficients results from the measurement error.

Few more tasks left beyond the paper draft:

- Test pip compatibility #30 
- Rewrite our notebook based on pip usage #32 
- Rewrite our documentation based on pip usage #31 
- Make our code binder compatible #29 
- Cleanup our code #26 
- Add proper citations and credits

**Comment by mn5hk** [comment]
Steps for a good flowchart:
![Uploading image.png…]()

**Comment by mn5hk** [comment]
Hi @abhimhamane , I read through the paper draft. Apologies on my part, the paper_joss.md file was somewhat outdated; and is incomplete. The more compete version is saved here: https://github.com/mn5hk/pyshbundle/blob/main/paper.md. I should have been more clear while communicating.

Would it be possible to rerun the JOSS action file, pointing towards this file? The changes you have incorporated to the previous file needs to be reflected in the new file as well (orcids, equations, table, etc).

**Comment by mn5hk** [comment]
@abhimhamane The paper draft (.pdf) has only four references, while the current draft has more references attached to it

**Comment by abhimhamane** [comment]
Hi @mn5hk , I'll make the necessary changes to the `paper.md` and look into the issue with references. I'll send you the updated `.pdf` ASAP.
