### ISSUE TITLE
Customize "Help" function in Python script

### ISSUE THREAD

**Issue by mn5hk** [mn5hk/pyshbundle#40]
Customize a help function in the python script. The function should return the script definition, author contribution, prior contribution attribution, and how to run the script.

More details on how to achieve this: https://stackoverflow.com/questions/21930035/how-to-write-help-description-text-for-python-functions

![image](https://user-images.githubusercontent.com/65601810/219277877-a580916c-0b67-4b82-ad60-bcbd7322c5ce.png)

![image](https://user-images.githubusercontent.com/65601810/219278605-dca429f3-8820-4a66-b767-c743d0f73ca4.png)

**Comment by lsmvivek** [comment]
Can we make this a _enchancement_ instead?

**Comment by mn5hk** [comment]
Hi @lsmvivek the documentation needs to be reasonably good overall. Sharing the review criteria of the journal here: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by lsmvivek** [comment]
Added in v0.3.0

**Comment by lsmvivek** [comment]
Added in v0.3.0
