### ISSUE TITLE
Minor formating issue in paper_with_equation.md

### ISSUE THREAD

**Issue by abhimhamane** [mn5hk/pyshbundle#47]
![Screenshot from 2023-04-06 17-16-38](https://user-images.githubusercontent.com/97011961/230368318-c206b783-dde8-41b7-ac00-397111b3908a.png)

The validation section of the file paper_with_equation.md has a minor formatting error, primarily due to the missing closing tag. It is a simple fix. May I fix this issue?

**Comment by mn5hk** [comment]
Hi @abhimhamane, thank you for your interest and for going through the repository. We will soon likely be deleting the file, hence updating it will not be necessary.

I will follow up in a few days.

Best,
AS
