### ISSUE TITLE
Orcid ID

### ISSUE THREAD

**Issue by mn5hk** [mn5hk/pyshbundle#52]
Hi all, request you to create an orcid id https://orcid.org/ and to share your id with me

**Comment by Walling9** [comment]
Hi Amin,

Hope you are keeping well. This is my Orcid ID: https://orcid.org/0009-0006-9323-1191

Regards,
Walling
________________________________

**Comment by abhimhamane** [comment]
Hi,

My Orcid Id is: https://orcid.org/0000-0001-9788-0371 . l'll update the Orcid Ids in the `paper_joss.md` affiliations section as and when I see anyone post it here. 

Regards,
Abhishek
