### ISSUE TITLE
Licensing: Creative commons or GPL

### ISSUE THREAD

**Issue by mn5hk** [mn5hk/pyshbundle#53]
https://www.diffen.com/difference/Creative_Commons_License_vs_GPL

**Comment by mn5hk** [comment]
@abhimhamane as we are building on existing GNU/GPL contributions, our package license also needs to be GNU/GPL. Currently, the paper draft license reads CC4.0 (which is more restrictive than GNU/GPL; and thus not allowed when working with GNU/GPL products). Request you to explore correct way to ensure proper license attribute to the paper draft.

**Comment by abhimhamane** [comment]
@mn5hk Yeah, sure I was also thinking about the same thing, the original SHBundle is distributed under GNU GPL license. The documentation for the SHBundle says: 

![Screenshot from 2023-04-18 22-15-55](https://user-images.githubusercontent.com/97011961/232847620-8cd0b24f-6407-4d70-b89a-35a110ff83b6.png)

But we are writing our own code in a different language, its more like an inspiration rather that redistribution or modification. I will read about the different licensing available and which one would be best suited for this project. There are lot of Python libraries which have translated code-bases from legacy languages like Fortran/C, so we could use similar licensing theme.

**Comment by mn5hk** [comment]
@abhimhamane I think GNU/GPL license will be more appropriate for our package. Do check if JOSS allows this licensing, thanks

**Comment by mn5hk** [comment]
Might be a useful discussion: https://github.com/openjournals/joss/issues/248

**Comment by mn5hk** [comment]
@abhimhamane I received a response here. License will not be an issue: https://github.com/openjournals/joss/issues/1215
