### ISSUE TITLE
Create a pypi account

### ISSUE THREAD

**Issue by mn5hk** [mn5hk/pyshbundle#57]
Hi @abhimhamane, I request you to create a pypi account. I will then invite you to be a collaborator for the pyshbundle project: https://pypi.org/manage/project/pyshbundle

The repository is close to being ready for publication. Since you are doing most of the new updates, it may be a good idea for you to have access to pypi.

Also, hope it would be a good opportunity to learn end-to-end python geodetic package publication.

Best,
AS

**Comment by abhimhamane** [comment]
I've created my PyPi account username - abhimhamane.

Regards,
Abhishek

**Comment by mn5hk** [comment]
Hi @abhimhamane , I have sent you a request as a collaborator

Thanks,
AS
