### ISSUE TITLE
Show datagaps in our results

### ISSUE THREAD

**Issue by mn5hk** [mn5hk/pyshbundle#60]
Hi @abhimhamane , in our current tutorial notebook, we achieve TWSA time-series for a river basin. However, the result we get is a continuous time-series.

![image](https://user-images.githubusercontent.com/65601810/236914315-748c6518-fcc1-42e2-abb3-503da8d60a9c.png)

This however is misleading as this hides our data gaps. GRACE has some months where we have no data for those months. To carry out some of the operations for gsha and gshs computation, we had to interpolate the data to receive a continuous time-series as input. However, we have not retained the original time-series over time (new time-series have data filled in place of No Data).

To not largely affect the current workflow, I would propose developing a new function that creates a mask for months with data gaps. This mask can later independently be plugged in for any of our outputs to get a more realistic representation of our GRACE outputs with data gaps.

Could you possibly have a look into the code in this direction? You may need more support to understand the code package, feel free to get in touch with me in this regard. I should be available this Sunday for some discussion. 

Also, please let me know if you can run the code with the package and descriptions for data access here. This would also be important feedback to ensure the general audience can use this code package without much hindrance.

Thank you for your amazing collaboration,
AS

**Comment by mn5hk** [comment]
I believe naninterp function could be modified for the purpose. Maybe have an optional argument parse into the function, which if flagged, also outputs the nan mask.

https://github.com/mn5hk/pyshbundle/blob/main/pyshbundle/naninterp.py

**Comment by abhimhamane** [comment]
Hi @mn5hk , sorry for late reply. I'll start working on the function, I was playing with the module with regards to documentation, I'll ask you my doubts regarding the workings on sunday or whenever you are free.

I need further clarification regarding the last para - "if you can run the code with the package and descriptions for data access here." 

Thanks,
Abhishek
