### ISSUE TITLE
clm2cs conversion  - function has no return statement

### ISSUE THREAD

**Issue by abhimhamane** [mn5hk/pyshbundle#62]
While I was exploring the module and trying different things, I could not convert the input SH data in `clm` format to `cs` format. I checked with both the dev version as well as published version of `clm2cs.py`. I think the issue is related to the function not returning anything. 

I guess the print statement also needs to be changed, `conversion from clm to cs format complete` might be a better alternative.

Here are the snippets from my code editor.
![Screenshot from 2023-05-10 13-54-10](https://github.com/mn5hk/pyshbundle/assets/97011961/d804c74c-2fd3-428c-bd7f-3f97919451a8)
I have checked the change history on github and it seems return statement was never added for this function

Thanks,
Abhishek

**Comment by mn5hk** [comment]
Hi @abhimhamane , indeed this is strange. Feel free to add the return statement.
