### ISSUE TITLE
Produce new plots

### ISSUE THREAD

**Issue by mn5hk** [mn5hk/pyshbundle#65]
In our current document, we have two plots for Ganges and Amazon as shown below.

Request a new plot to replace these plots. The idea would be to have a single plot. In the plot, we have TWS basin average for both Ganges and Amazon from both pyshbundle and shbundle. Further, we make the blue lines for pyshbundle plots thickness as say 4 and red lines for shbundle plot thickness as say 2.

This way, the information will be more concise and comprehensive. Also, data gaps need to be represented as discussed in #60 .

![image](https://github.com/mn5hk/pyshbundle/assets/65601810/c5e4f412-b4da-4926-99b4-93ed74286058)

**Comment by abhimhamane** [comment]
Yeah, this idea seems to be much more compact and intuitive. I'm working on data gaps, I have not yet figured out how to tackle the data gaps, I'll do it by the end of this week.
