### ISSUE TITLE
Line77: Show CLM, SLM and KLM data in matrix format

### ISSUE THREAD

**Issue by mn5hk** [mn5hk/pyshbundle#67]
Hi @abhimhamane,

As per comments in draft in line 77, could you generate matrices for the three data formats?

Thanks,
AS

**Comment by abhimhamane** [comment]
I can write those matrices in latex similar to those presented in SHBundle docs.

/S|C\ format - 
![Screenshot from 2023-05-23 22-37-30](https://github.com/mn5hk/pyshbundle/assets/97011961/9385427a-a50b-4cbd-942f-50130f528ca8)

|C\S| format - 
![Screenshot from 2023-05-23 22-37-49](https://github.com/mn5hk/pyshbundle/assets/97011961/1e50ea01-4a59-45ab-8517-c22a20385f90)

klm format - 
![klm](https://github.com/mn5hk/pyshbundle/assets/97011961/390264a0-af3e-4bb9-8379-f67b851a5c0b)
