### ISSUE TITLE
Major Tasks to be done ASAP

### ISSUE THREAD

**Issue by abhimhamane** [mn5hk/pyshbundle#68]
I'm compiling all the current major tasks as a to-do list here alongside tasks in issue #61  , as per discussion with Prof. Bramha and @mn5hk 

High Priority
- [x]  `clm2cs` bug
  - [x] another implementation with `clm2sc` and `sc2cs`
  - [x] Issue with zonal std. deviations being zero [Not relevant now with new implementation]
- [x]  `reader_replacer_csr` currently takes hours to run (basically infinite loop)
- [x] New implementation runs quite well
  - [x] The issue of date mismatch been solved using the Vivek's approach of timedelta of 5 and 23 days
  - [x]  New implementation has some errors in the downstream processing ( this issue solved...mostly trivial error(
  - [x] Need to check the old & new implementation of klm2sc (implemented klm2sc fucntion for new reading implementation)
  - [x] Equivalance check with new and Vivek's reading/replacement shows some discrepancies but mostly minor)
- [ ]  Write independent function for filtering of GRACE data - mainly Gaussian to start with
- [x]  Show Data gaps in the time-series plot
- [ ]  `gshs` issue with some quantities like `geoid` and `potential`
  - [x] the ones in SHBundle were resolved
  - [ ] the `height` quantity is remaining
- [x]  Independent visualisation utility
   - [x] sctriplot
   - [x] mapfield
       - [x] Normal
       - [x] Greenland and Antarctica
- [x]  Compute basin-average time-series using SHBundle for comparision purpose (instead using older data)
- [x]  Add new feature: extract standard deviations from L2 products

Medium Priority
- [x] Check if the current implementation works for single data file
- [ ] add de-correlation fliter and other different kinds of filter options
- [x]  Add progress bar instead of current print output for `reader_replacer` functions [Not relevant with new implementation]
- [x]  reorganize `reader_replacer` as per issue #61 
- [ ]  Docs and tutorials
   - [ ] for grace data driven correction
   - [x] intro to spherical harmonics using pyshbundle
   - [x] loading data 
   - [ ] TWS time series
- [x]  Function to check the format of SH data
- [x] The `normalklm.py` function had inconsistency with lmax usage -> solved -- lmax=96 => shape(97, 97)

**Comment by abhimhamane** [comment]
@mn5hk and @lsmvivek ,

From the testing [with one of the static geoid model files] I found all the quantities in `SHBundle` seem to work properly, The issue in `PySHBundle` implementation was regarding the shape and size of vector being generated by `eigengrav` function.

The required shape should have been of $(1,  l_{max})$. Now the `gshs` function works well, except the `height` implementation still has issue as it was not implemented in `SHBundle`.

Example plot - 
![image](https://github.com/mn5hk/pyshbundle/assets/97011961/5f6968d1-6393-4051-af8f-e782d56c0578)

**Comment by mn5hk** [comment]
Hi @abhimhamane , thanks; could the output of `eigengrav` be modified to the required shape? Would this affect the current workflow negatively somehow?

**Comment by mn5hk** [comment]
Regarding `gshs`, please feel free to update the new options into the code, if feasible.

Thanks,
AS

**Comment by abhimhamane** [comment]
Hi @mn5hk and @lsmvivek 

Sorry for very delayed update, I was bit busy with my reading for my thesis and GRE prep.

I could not get around the current `reader_replacer_csr` implementation, hence I thought that I'll follow the similar process but make it for single file so that its bit simple to debug for potential errors. I have implemented my own version for reading and replacing coefficients. 

Unlike the current implementation, I'm storing dates and data saperately as matrices. Storing data as matrices allow for vector operations which are way efficient and less complicated when compared to loops. I have tested them for all the data formats and it seems to work. 

![image](https://github.com/mn5hk/pyshbundle/assets/97011961/e5610384-6049-4c67-aafb-b29d6c7a4254)
This is for std. deviations for one of the CSR files. The white block seems consistent with the data. 

Regards,
Abhishek

**Comment by mn5hk** [comment]
Thanks for the update, @abhimhamane

**Comment by abhimhamane** [comment]
Update on date mismatch issue while replacing the lower degree coefficients.
I have used the Vivek's approach of using timedelta of 5 days for CSR and 23 days for ITSG. The replacing is working fine.

**Comment by abhimhamane** [comment]
New file reading and replacement update,

*For JPL - data and std. deviations*

From the equivalence plot it can be seen that there is discrepancies with C30
![image](https://github.com/mn5hk/pyshbundle/assets/97011961/9e2252d6-3029-4bac-a5d8-51c86c5a5012)



For the std. deviations there is some systematic error either in mine or vivek's code still need to investigate
![image](https://github.com/mn5hk/pyshbundle/assets/97011961/44ac1477-7b28-4b98-8c80-09a44844b2d5)



*For CSR - data and std. deviations*

No errors with the reading and replacement of coeff.
![image](https://github.com/mn5hk/pyshbundle/assets/97011961/4de75c70-1562-424d-ae1e-1993c7759816)


Mostly replacement issue with C10 and S11 coeff.
![image](https://github.com/mn5hk/pyshbundle/assets/97011961/571a384d-7ffd-4d89-82a0-ca9e6dbb5878)


*For ITSG - data and std. deviations*

Error with replacement of coeff. for both data and std. deviations
![image](https://github.com/mn5hk/pyshbundle/assets/97011961/36204438-e16b-48bb-bdc9-bbbf1f688c20)


I'm trying to troubleshoot and solve the bug.

**Comment by mn5hk** [comment]
> New file reading and replacement update,
> 
> *For JPL - data and std. deviations*
> 
> From the equivalence plot it can be seen that there is discrepancies with C30
> ![image](https://github.com/mn5hk/pyshbundle/assets/97011961/9e2252d6-3029-4bac-a5d8-51c86c5a5012)
> 
> 
> 
> For the std. deviations there is some systematic error either in mine or vivek's code still need to investigate
> ![image](https://github.com/mn5hk/pyshbundle/assets/97011961/44ac1477-7b28-4b98-8c80-09a44844b2d5)
> 
> 
> 
> *For CSR - data and std. deviations*
> 
> No errors with the reading and replacement of coeff.
> ![image](https://github.com/mn5hk/pyshbundle/assets/97011961/4de75c70-1562-424d-ae1e-1993c7759816)
> 
> 
> Mostly replacement issue with C10 and S11 coeff.
> ![image](https://github.com/mn5hk/pyshbundle/assets/97011961/571a384d-7ffd-4d89-82a0-ca9e6dbb5878)
> 
> 
> *For ITSG - data and std. deviations*
> 
> Error with replacement of coeff. for both data and std. deviations
> ![image](https://github.com/mn5hk/pyshbundle/assets/97011961/36204438-e16b-48bb-bdc9-bbbf1f688c20)
> 
> 
> I'm trying to troubleshoot and solve the bug.

Thanks for the update

**Comment by mn5hk** [comment]
Thanks @abhimhamane for your tremendous contributions :)
