### ISSUE TITLE
pip compatibility

### ISSUE THREAD

**Issue by mn5hk** [mn5hk/pyshbundle#89]
- [x] create a new pip release https://pypi.org/manage/project/pyshbundle/release/0.0.3.2/
- [x] add all module names to __init__.py
- [x] test pip release
   - [x] Working on Linux Mint 21.3 with python 3.10.12
   - [x] Need to try on Windows 10
   - [x] Having issues installing with pip and using the newly built tar.gz  on windows only
- [x] make pip work
- [x] update tutorials with pip workflow
    - [x] Done, but there is an error - 'Module' Object not callable 
- [x] double check our module flowchart diagram to ensure it still makes sense

**Comment by mn5hk** [comment]
Dear @abhimhamane,

I have currently created a new pypi release v0.1.1 that seems to be working: https://pypi.org/manage/project/pyshbundle/release/0.1.1/

As you have been more involved in the development of the notebooks, if possible, I request you to update the notebooks by calling the pypi module.

In addition, couple other tasks may be necessary:
- Nomenclature of modules to me made more user-friendly [rename/replace clm2cs with clm2cs_new, for example)
![image](https://github.com/mn5hk/pyshbundle/assets/65601810/77892c29-ae65-4d4c-ad5a-06cb4e486968)

- Handle multiple functions with same name from different python modules (.py files) [maybe not calling some of it works, in case all of the modules perform the same activity)
![image](https://github.com/mn5hk/pyshbundle/assets/65601810/6e49de63-14ba-4801-aa1a-e1b7659ad707)

Lastly, please note that the development for the pypi module is currently being undertaken in a dedicated branch: `89-pip-compatibility`

Couple links that may be useful:
- https://github.com/mn5hk/pyshbundle/blob/89-pip-compatibility/pyshbundle/__init__.py
- https://github.com/mn5hk/pyshbundle/blob/89-pip-compatibility/test_AS_202401014.ipynb

Maybe we have a meeting sometime later to wrap up a release version.

Best,
AS

**Comment by abhimhamane** [comment]
![Screenshot from 2024-01-13 13-29-40](https://github.com/mn5hk/pyshbundle/assets/97011961/57fef17e-7e1e-48b2-b007-516fa7b1e9e4)
The error occuring in timeseries and visualization notebooks. The error being 'module' object is not callable. From some of the online discussion forums it seems that, there is a conflict when the file and function has the same name. Here's a snippet from - https://discuss.streamlit.io/t/error-when-deploying-app-with-stream-select-menu/34711/5
![Screenshot from 2024-01-13 16-10-41](https://github.com/mn5hk/pyshbundle/assets/97011961/1e6998f0-460b-4511-a1c2-20921462a31b)

I've tried using aliases to call functions but it does not work. One solution is to reorganize the functions as per their utility 
1. ioutils - reading data files
2. graceshutils - SH processing of grace
3. hydrograce - tws, basin avg and other hydrological application of grace data
4. vizutils - visualization

**Comment by abhimhamane** [comment]
Reorganization is a bit more time-consuming. An easy fix for the initial release is to use a slightly different function name.
- gaussian -> Gaussian
- tws_cal -> TWSCalc
- basin_avg -> BasinAvg
This works fine as there is no conflict b/w the module and function name.

**Comment by abhimhamane** [comment]
Error with uploading to PyPi using Twine
![Screenshot from 2024-01-13 19-12-07](https://github.com/mn5hk/pyshbundle/assets/97011961/2f8d0404-047b-40f0-8ce1-27374aabe99d)

Also error related to sub-processor module while installing the module from tar.gz on windows. It needs to be looked into.
